---
title: "MPG Surveys"
output:
  flexdashboard::flex_dashboard: 
    theme: spacelab
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(leaflet)
library(tidyverse)
library(DT)
library(shinyWidgets)
library(bigrquery)

# Warehouse Connection
# BigQuery API Key
bq_auth(path = "keys/mpg-data-warehouse-api_key-master.json")
Sys.setenv(BIGQUERY_TEST_PROJECT = "mpg-data-warehouse")
billing <- bq_test_project()
```

```{r}
# vegetation_gridVeg_summaries
sql_surveys <- "
  SELECT * FROM `mpg-data-warehouse.grid_point_summaries.survey_summary`
" 
bq_surveys <- bq_project_query(billing, sql_surveys)
tb_surveys <- bq_table_download(bq_surveys)
df_surveys <- as.data.frame(tb_surveys)
```

Sidebar {.sidebar data-width=300}
=====================================
<br>
```{r}
# Find unique surveys in dataset
distinct_surveys <- df_surveys %>%
  select(survey) %>%
  distinct(survey)

# Show surveys
pickerInput(inputId = "survey_selection",
            label = "Show Survey:",
            choices = distinct_surveys,
            selected = "vegetation_biomass",
            multiple = TRUE,
            options = list(`actions-box` = TRUE)
            )

# Based on user survey selection show available years
distinct_years <- reactive({
  df_surveys %>%
    filter(survey %in% input$survey_selection) %>%
    select(year) %>%
    distinct(year) %>%
    arrange(desc(year))
  })

# Show years
renderUI({
  pickerInput(inputId = "year_selection",
            label = "Show Year:",
            choices = distinct_years(),
            selected = distinct_years()$year[1],
            multiple = TRUE,
            options = list(`actions-box` = TRUE)
            )
})

# Show all gridpoints
gridpoints_all <- df_surveys %>%
  select(grid_point, lat, long) %>%
  distinct(grid_point, lat, long)

# Show gridpoints
gridpoints_selected <- reactive({
  df_surveys %>%
    select(grid_point, lat, long, year, survey) %>%
    filter(year %in% input$year_selection & survey %in% input$survey_selection) %>%
    distinct(grid_point, lat, long)
})

# Highlight survey
pickerInput(inputId = "survey_highlight",
            label = "Highlight Survey:",
            choices = distinct_surveys,
            selected = "",
            multiple = TRUE,
            options = list(`actions-box` = TRUE)
            )

# Show available years for highlight
distinct_years_high <- reactive({
  df_surveys %>%
    filter(survey %in% input$survey_highlight) %>%
    select(year) %>%
    distinct(year) %>%
    arrange(desc(year))
  })

# Pick Highlight years
renderUI({
  pickerInput(inputId = "year_highlight",
            label = "Highlight Year:",
            choices = distinct_years_high(),
            selected = distinct_years_high()$year[1],
            multiple = TRUE,
            options = list(`actions-box` = TRUE)
            )
})

# Highlight gridpoints
gridpoints_highlighted <- reactive({
  df_surveys %>%
    select(grid_point, lat, long, year, survey) %>%
    filter(year %in% input$year_highlight & survey %in% input$survey_highlight) %>%
    distinct(grid_point, lat, long)
})
```

Map {.tabset data-width=700}
=====================================

```{r}
output$map_base <- renderLeaflet({
  leaflet(options = leafletOptions(zoomControl = TRUE,
                                 minZoom = 12, maxZoom = 16)) %>%
    setView(-114.001, 46.70, zoom = 13) %>%
    addWMSTiles("https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryTopo/MapServer/tile/{z}/{y}/{x}", 
                layers = "OpenTopoMap")
  })
  
observe({
  leafletProxy("map_base") %>%
  clearMarkers() %>%
  addCircleMarkers(gridpoints_all$long, gridpoints_all$lat, 
                 color = 'x',
                 radius = 17, popup = as.character(gridpoints_all$grid_point)) %>%
  addCircleMarkers(gridpoints_selected()$long, gridpoints_selected()$lat, radius = 5, color = 'yellow',
                   popup = as.character(gridpoints_selected()$grid_point)) %>%
  addCircleMarkers(gridpoints_highlighted()$long, gridpoints_highlighted()$lat, radius = 2, color = 'red', opacity = 1,
                   popup = as.character(gridpoints_highlighted()$grid_point))
})

leafletOutput("map_base", width = "100%", height = "100%")
```

Surveys
=====================================

Column {.tabset data-width=700}
-----------------
```{r}
gridpoints_table <- reactive({
  df_surveys %>% 
  select(-lat, -long) %>%
  filter((year %in% input$year_selection & survey %in% input$survey_selection)) %>%
  distinct(year, grid_point, survey) %>%
  mutate(grid_point = as.character(grid_point)) %>%
  arrange(year, grid_point, survey)
})

renderDT({
  datatable(
    gridpoints_table(), 
    rownames = FALSE,
    filter = "top",
    options = list(scrollY = '400px', scrollX = TRUE)
  )
})
```

Chart
=====================================

Column {.tabset data-width=700}
-----------------
```{r}
survey_chart <- reactive({
  df_surveys %>%
    filter((year %in% input$year_selection & survey %in% input$survey_selection)) %>%
    count(year, survey, name = "count")
})

renderPlot({
  ggplot(survey_chart(), aes(x = year)) +
    geom_bar(aes(weight = count, fill = survey), position = "dodge")
})
```